/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TBAAPI.V3Client.Api;
using TBAAPI.V3Client.Model;
using TBAAPI.V3Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TBAAPI.V3Client.Test
{
    /// <summary>
    ///  Class for testing DistrictRanking
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DistrictRankingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DistrictRanking
        //private DistrictRanking instance;

        public DistrictRankingTests()
        {
            // TODO uncomment below to create an instance of DistrictRanking
            //instance = new DistrictRanking();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DistrictRanking
        /// </summary>
        [Fact]
        public void DistrictRankingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DistrictRanking
            //Assert.IsInstanceOfType<DistrictRanking> (instance, "variable 'instance' is a DistrictRanking");
        }


        /// <summary>
        /// Test the property 'TeamKey'
        /// </summary>
        [Fact]
        public void TeamKeyTest()
        {
            // TODO unit test for the property 'TeamKey'
        }
        /// <summary>
        /// Test the property 'Rank'
        /// </summary>
        [Fact]
        public void RankTest()
        {
            // TODO unit test for the property 'Rank'
        }
        /// <summary>
        /// Test the property 'RookieBonus'
        /// </summary>
        [Fact]
        public void RookieBonusTest()
        {
            // TODO unit test for the property 'RookieBonus'
        }
        /// <summary>
        /// Test the property 'PointTotal'
        /// </summary>
        [Fact]
        public void PointTotalTest()
        {
            // TODO unit test for the property 'PointTotal'
        }
        /// <summary>
        /// Test the property 'EventPoints'
        /// </summary>
        [Fact]
        public void EventPointsTest()
        {
            // TODO unit test for the property 'EventPoints'
        }

    }

}
