/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TBAAPI.V3Client.Api;
using TBAAPI.V3Client.Model;
using TBAAPI.V3Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TBAAPI.V3Client.Test
{
    /// <summary>
    ///  Class for testing MatchScoreBreakdown2016
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatchScoreBreakdown2016Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MatchScoreBreakdown2016
        //private MatchScoreBreakdown2016 instance;

        public MatchScoreBreakdown2016Tests()
        {
            // TODO uncomment below to create an instance of MatchScoreBreakdown2016
            //instance = new MatchScoreBreakdown2016();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MatchScoreBreakdown2016
        /// </summary>
        [Fact]
        public void MatchScoreBreakdown2016InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MatchScoreBreakdown2016
            //Assert.IsInstanceOfType<MatchScoreBreakdown2016> (instance, "variable 'instance' is a MatchScoreBreakdown2016");
        }


        /// <summary>
        /// Test the property 'Blue'
        /// </summary>
        [Fact]
        public void BlueTest()
        {
            // TODO unit test for the property 'Blue'
        }
        /// <summary>
        /// Test the property 'Red'
        /// </summary>
        [Fact]
        public void RedTest()
        {
            // TODO unit test for the property 'Red'
        }

    }

}
