/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TBAAPI.V3Client.Api;
using TBAAPI.V3Client.Model;
using TBAAPI.V3Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TBAAPI.V3Client.Test
{
    /// <summary>
    ///  Class for testing MatchScoreBreakdown2019Alliance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatchScoreBreakdown2019AllianceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MatchScoreBreakdown2019Alliance
        //private MatchScoreBreakdown2019Alliance instance;

        public MatchScoreBreakdown2019AllianceTests()
        {
            // TODO uncomment below to create an instance of MatchScoreBreakdown2019Alliance
            //instance = new MatchScoreBreakdown2019Alliance();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MatchScoreBreakdown2019Alliance
        /// </summary>
        [Fact]
        public void MatchScoreBreakdown2019AllianceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MatchScoreBreakdown2019Alliance
            //Assert.IsInstanceOfType<MatchScoreBreakdown2019Alliance> (instance, "variable 'instance' is a MatchScoreBreakdown2019Alliance");
        }


        /// <summary>
        /// Test the property 'AdjustPoints'
        /// </summary>
        [Fact]
        public void AdjustPointsTest()
        {
            // TODO unit test for the property 'AdjustPoints'
        }
        /// <summary>
        /// Test the property 'AutoPoints'
        /// </summary>
        [Fact]
        public void AutoPointsTest()
        {
            // TODO unit test for the property 'AutoPoints'
        }
        /// <summary>
        /// Test the property 'Bay1'
        /// </summary>
        [Fact]
        public void Bay1Test()
        {
            // TODO unit test for the property 'Bay1'
        }
        /// <summary>
        /// Test the property 'Bay2'
        /// </summary>
        [Fact]
        public void Bay2Test()
        {
            // TODO unit test for the property 'Bay2'
        }
        /// <summary>
        /// Test the property 'Bay3'
        /// </summary>
        [Fact]
        public void Bay3Test()
        {
            // TODO unit test for the property 'Bay3'
        }
        /// <summary>
        /// Test the property 'Bay4'
        /// </summary>
        [Fact]
        public void Bay4Test()
        {
            // TODO unit test for the property 'Bay4'
        }
        /// <summary>
        /// Test the property 'Bay5'
        /// </summary>
        [Fact]
        public void Bay5Test()
        {
            // TODO unit test for the property 'Bay5'
        }
        /// <summary>
        /// Test the property 'Bay6'
        /// </summary>
        [Fact]
        public void Bay6Test()
        {
            // TODO unit test for the property 'Bay6'
        }
        /// <summary>
        /// Test the property 'Bay7'
        /// </summary>
        [Fact]
        public void Bay7Test()
        {
            // TODO unit test for the property 'Bay7'
        }
        /// <summary>
        /// Test the property 'Bay8'
        /// </summary>
        [Fact]
        public void Bay8Test()
        {
            // TODO unit test for the property 'Bay8'
        }
        /// <summary>
        /// Test the property 'CargoPoints'
        /// </summary>
        [Fact]
        public void CargoPointsTest()
        {
            // TODO unit test for the property 'CargoPoints'
        }
        /// <summary>
        /// Test the property 'CompleteRocketRankingPoint'
        /// </summary>
        [Fact]
        public void CompleteRocketRankingPointTest()
        {
            // TODO unit test for the property 'CompleteRocketRankingPoint'
        }
        /// <summary>
        /// Test the property 'CompletedRocketFar'
        /// </summary>
        [Fact]
        public void CompletedRocketFarTest()
        {
            // TODO unit test for the property 'CompletedRocketFar'
        }
        /// <summary>
        /// Test the property 'CompletedRocketNear'
        /// </summary>
        [Fact]
        public void CompletedRocketNearTest()
        {
            // TODO unit test for the property 'CompletedRocketNear'
        }
        /// <summary>
        /// Test the property 'EndgameRobot1'
        /// </summary>
        [Fact]
        public void EndgameRobot1Test()
        {
            // TODO unit test for the property 'EndgameRobot1'
        }
        /// <summary>
        /// Test the property 'EndgameRobot2'
        /// </summary>
        [Fact]
        public void EndgameRobot2Test()
        {
            // TODO unit test for the property 'EndgameRobot2'
        }
        /// <summary>
        /// Test the property 'EndgameRobot3'
        /// </summary>
        [Fact]
        public void EndgameRobot3Test()
        {
            // TODO unit test for the property 'EndgameRobot3'
        }
        /// <summary>
        /// Test the property 'FoulCount'
        /// </summary>
        [Fact]
        public void FoulCountTest()
        {
            // TODO unit test for the property 'FoulCount'
        }
        /// <summary>
        /// Test the property 'FoulPoints'
        /// </summary>
        [Fact]
        public void FoulPointsTest()
        {
            // TODO unit test for the property 'FoulPoints'
        }
        /// <summary>
        /// Test the property 'HabClimbPoints'
        /// </summary>
        [Fact]
        public void HabClimbPointsTest()
        {
            // TODO unit test for the property 'HabClimbPoints'
        }
        /// <summary>
        /// Test the property 'HabDockingRankingPoint'
        /// </summary>
        [Fact]
        public void HabDockingRankingPointTest()
        {
            // TODO unit test for the property 'HabDockingRankingPoint'
        }
        /// <summary>
        /// Test the property 'HabLineRobot1'
        /// </summary>
        [Fact]
        public void HabLineRobot1Test()
        {
            // TODO unit test for the property 'HabLineRobot1'
        }
        /// <summary>
        /// Test the property 'HabLineRobot2'
        /// </summary>
        [Fact]
        public void HabLineRobot2Test()
        {
            // TODO unit test for the property 'HabLineRobot2'
        }
        /// <summary>
        /// Test the property 'HabLineRobot3'
        /// </summary>
        [Fact]
        public void HabLineRobot3Test()
        {
            // TODO unit test for the property 'HabLineRobot3'
        }
        /// <summary>
        /// Test the property 'HatchPanelPoints'
        /// </summary>
        [Fact]
        public void HatchPanelPointsTest()
        {
            // TODO unit test for the property 'HatchPanelPoints'
        }
        /// <summary>
        /// Test the property 'LowLeftRocketFar'
        /// </summary>
        [Fact]
        public void LowLeftRocketFarTest()
        {
            // TODO unit test for the property 'LowLeftRocketFar'
        }
        /// <summary>
        /// Test the property 'LowLeftRocketNear'
        /// </summary>
        [Fact]
        public void LowLeftRocketNearTest()
        {
            // TODO unit test for the property 'LowLeftRocketNear'
        }
        /// <summary>
        /// Test the property 'LowRightRocketFar'
        /// </summary>
        [Fact]
        public void LowRightRocketFarTest()
        {
            // TODO unit test for the property 'LowRightRocketFar'
        }
        /// <summary>
        /// Test the property 'LowRightRocketNear'
        /// </summary>
        [Fact]
        public void LowRightRocketNearTest()
        {
            // TODO unit test for the property 'LowRightRocketNear'
        }
        /// <summary>
        /// Test the property 'MidLeftRocketFar'
        /// </summary>
        [Fact]
        public void MidLeftRocketFarTest()
        {
            // TODO unit test for the property 'MidLeftRocketFar'
        }
        /// <summary>
        /// Test the property 'MidLeftRocketNear'
        /// </summary>
        [Fact]
        public void MidLeftRocketNearTest()
        {
            // TODO unit test for the property 'MidLeftRocketNear'
        }
        /// <summary>
        /// Test the property 'MidRightRocketFar'
        /// </summary>
        [Fact]
        public void MidRightRocketFarTest()
        {
            // TODO unit test for the property 'MidRightRocketFar'
        }
        /// <summary>
        /// Test the property 'MidRightRocketNear'
        /// </summary>
        [Fact]
        public void MidRightRocketNearTest()
        {
            // TODO unit test for the property 'MidRightRocketNear'
        }
        /// <summary>
        /// Test the property 'PreMatchBay1'
        /// </summary>
        [Fact]
        public void PreMatchBay1Test()
        {
            // TODO unit test for the property 'PreMatchBay1'
        }
        /// <summary>
        /// Test the property 'PreMatchBay2'
        /// </summary>
        [Fact]
        public void PreMatchBay2Test()
        {
            // TODO unit test for the property 'PreMatchBay2'
        }
        /// <summary>
        /// Test the property 'PreMatchBay3'
        /// </summary>
        [Fact]
        public void PreMatchBay3Test()
        {
            // TODO unit test for the property 'PreMatchBay3'
        }
        /// <summary>
        /// Test the property 'PreMatchBay6'
        /// </summary>
        [Fact]
        public void PreMatchBay6Test()
        {
            // TODO unit test for the property 'PreMatchBay6'
        }
        /// <summary>
        /// Test the property 'PreMatchBay7'
        /// </summary>
        [Fact]
        public void PreMatchBay7Test()
        {
            // TODO unit test for the property 'PreMatchBay7'
        }
        /// <summary>
        /// Test the property 'PreMatchBay8'
        /// </summary>
        [Fact]
        public void PreMatchBay8Test()
        {
            // TODO unit test for the property 'PreMatchBay8'
        }
        /// <summary>
        /// Test the property 'PreMatchLevelRobot1'
        /// </summary>
        [Fact]
        public void PreMatchLevelRobot1Test()
        {
            // TODO unit test for the property 'PreMatchLevelRobot1'
        }
        /// <summary>
        /// Test the property 'PreMatchLevelRobot2'
        /// </summary>
        [Fact]
        public void PreMatchLevelRobot2Test()
        {
            // TODO unit test for the property 'PreMatchLevelRobot2'
        }
        /// <summary>
        /// Test the property 'PreMatchLevelRobot3'
        /// </summary>
        [Fact]
        public void PreMatchLevelRobot3Test()
        {
            // TODO unit test for the property 'PreMatchLevelRobot3'
        }
        /// <summary>
        /// Test the property 'Rp'
        /// </summary>
        [Fact]
        public void RpTest()
        {
            // TODO unit test for the property 'Rp'
        }
        /// <summary>
        /// Test the property 'SandStormBonusPoints'
        /// </summary>
        [Fact]
        public void SandStormBonusPointsTest()
        {
            // TODO unit test for the property 'SandStormBonusPoints'
        }
        /// <summary>
        /// Test the property 'TechFoulCount'
        /// </summary>
        [Fact]
        public void TechFoulCountTest()
        {
            // TODO unit test for the property 'TechFoulCount'
        }
        /// <summary>
        /// Test the property 'TeleopPoints'
        /// </summary>
        [Fact]
        public void TeleopPointsTest()
        {
            // TODO unit test for the property 'TeleopPoints'
        }
        /// <summary>
        /// Test the property 'TopLeftRocketFar'
        /// </summary>
        [Fact]
        public void TopLeftRocketFarTest()
        {
            // TODO unit test for the property 'TopLeftRocketFar'
        }
        /// <summary>
        /// Test the property 'TopLeftRocketNear'
        /// </summary>
        [Fact]
        public void TopLeftRocketNearTest()
        {
            // TODO unit test for the property 'TopLeftRocketNear'
        }
        /// <summary>
        /// Test the property 'TopRightRocketFar'
        /// </summary>
        [Fact]
        public void TopRightRocketFarTest()
        {
            // TODO unit test for the property 'TopRightRocketFar'
        }
        /// <summary>
        /// Test the property 'TopRightRocketNear'
        /// </summary>
        [Fact]
        public void TopRightRocketNearTest()
        {
            // TODO unit test for the property 'TopRightRocketNear'
        }
        /// <summary>
        /// Test the property 'TotalPoints'
        /// </summary>
        [Fact]
        public void TotalPointsTest()
        {
            // TODO unit test for the property 'TotalPoints'
        }

    }

}
