/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TBAAPI.V3Client.Api;
using TBAAPI.V3Client.Model;
using TBAAPI.V3Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TBAAPI.V3Client.Test
{
    /// <summary>
    ///  Class for testing TeamEventStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TeamEventStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TeamEventStatus
        //private TeamEventStatus instance;

        public TeamEventStatusTests()
        {
            // TODO uncomment below to create an instance of TeamEventStatus
            //instance = new TeamEventStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TeamEventStatus
        /// </summary>
        [Fact]
        public void TeamEventStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TeamEventStatus
            //Assert.IsInstanceOfType<TeamEventStatus> (instance, "variable 'instance' is a TeamEventStatus");
        }


        /// <summary>
        /// Test the property 'Qual'
        /// </summary>
        [Fact]
        public void QualTest()
        {
            // TODO unit test for the property 'Qual'
        }
        /// <summary>
        /// Test the property 'Alliance'
        /// </summary>
        [Fact]
        public void AllianceTest()
        {
            // TODO unit test for the property 'Alliance'
        }
        /// <summary>
        /// Test the property 'Playoff'
        /// </summary>
        [Fact]
        public void PlayoffTest()
        {
            // TODO unit test for the property 'Playoff'
        }
        /// <summary>
        /// Test the property 'AllianceStatusStr'
        /// </summary>
        [Fact]
        public void AllianceStatusStrTest()
        {
            // TODO unit test for the property 'AllianceStatusStr'
        }
        /// <summary>
        /// Test the property 'PlayoffStatusStr'
        /// </summary>
        [Fact]
        public void PlayoffStatusStrTest()
        {
            // TODO unit test for the property 'PlayoffStatusStr'
        }
        /// <summary>
        /// Test the property 'OverallStatusStr'
        /// </summary>
        [Fact]
        public void OverallStatusStrTest()
        {
            // TODO unit test for the property 'OverallStatusStr'
        }
        /// <summary>
        /// Test the property 'NextMatchKey'
        /// </summary>
        [Fact]
        public void NextMatchKeyTest()
        {
            // TODO unit test for the property 'NextMatchKey'
        }
        /// <summary>
        /// Test the property 'LastMatchKey'
        /// </summary>
        [Fact]
        public void LastMatchKeyTest()
        {
            // TODO unit test for the property 'LastMatchKey'
        }

    }

}
