/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TBAAPI.V3Client.Api;
using TBAAPI.V3Client.Model;
using TBAAPI.V3Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TBAAPI.V3Client.Test
{
    /// <summary>
    ///  Class for testing TeamEventStatusRank
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TeamEventStatusRankTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TeamEventStatusRank
        //private TeamEventStatusRank instance;

        public TeamEventStatusRankTests()
        {
            // TODO uncomment below to create an instance of TeamEventStatusRank
            //instance = new TeamEventStatusRank();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TeamEventStatusRank
        /// </summary>
        [Fact]
        public void TeamEventStatusRankInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TeamEventStatusRank
            //Assert.IsInstanceOfType<TeamEventStatusRank> (instance, "variable 'instance' is a TeamEventStatusRank");
        }


        /// <summary>
        /// Test the property 'NumTeams'
        /// </summary>
        [Fact]
        public void NumTeamsTest()
        {
            // TODO unit test for the property 'NumTeams'
        }
        /// <summary>
        /// Test the property 'Ranking'
        /// </summary>
        [Fact]
        public void RankingTest()
        {
            // TODO unit test for the property 'Ranking'
        }
        /// <summary>
        /// Test the property 'SortOrderInfo'
        /// </summary>
        [Fact]
        public void SortOrderInfoTest()
        {
            // TODO unit test for the property 'SortOrderInfo'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
