/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TBAAPI.V3Client.Api;
using TBAAPI.V3Client.Model;
using TBAAPI.V3Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TBAAPI.V3Client.Test
{
    /// <summary>
    ///  Class for testing TeamRobot
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TeamRobotTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TeamRobot
        //private TeamRobot instance;

        public TeamRobotTests()
        {
            // TODO uncomment below to create an instance of TeamRobot
            //instance = new TeamRobot();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TeamRobot
        /// </summary>
        [Fact]
        public void TeamRobotInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TeamRobot
            //Assert.IsInstanceOfType<TeamRobot> (instance, "variable 'instance' is a TeamRobot");
        }


        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'RobotName'
        /// </summary>
        [Fact]
        public void RobotNameTest()
        {
            // TODO unit test for the property 'RobotName'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'TeamKey'
        /// </summary>
        [Fact]
        public void TeamKeyTest()
        {
            // TODO unit test for the property 'TeamKey'
        }

    }

}
