/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TBAAPI.V3Client.Api;
using TBAAPI.V3Client.Model;
using TBAAPI.V3Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TBAAPI.V3Client.Test
{
    /// <summary>
    ///  Class for testing Team
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TeamTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Team
        //private Team instance;

        public TeamTests()
        {
            // TODO uncomment below to create an instance of Team
            //instance = new Team();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Team
        /// </summary>
        [Fact]
        public void TeamInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Team
            //Assert.IsInstanceOfType<Team> (instance, "variable 'instance' is a Team");
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'TeamNumber'
        /// </summary>
        [Fact]
        public void TeamNumberTest()
        {
            // TODO unit test for the property 'TeamNumber'
        }
        /// <summary>
        /// Test the property 'Nickname'
        /// </summary>
        [Fact]
        public void NicknameTest()
        {
            // TODO unit test for the property 'Nickname'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SchoolName'
        /// </summary>
        [Fact]
        public void SchoolNameTest()
        {
            // TODO unit test for the property 'SchoolName'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'StateProv'
        /// </summary>
        [Fact]
        public void StateProvTest()
        {
            // TODO unit test for the property 'StateProv'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'GmapsPlaceId'
        /// </summary>
        [Fact]
        public void GmapsPlaceIdTest()
        {
            // TODO unit test for the property 'GmapsPlaceId'
        }
        /// <summary>
        /// Test the property 'GmapsUrl'
        /// </summary>
        [Fact]
        public void GmapsUrlTest()
        {
            // TODO unit test for the property 'GmapsUrl'
        }
        /// <summary>
        /// Test the property 'Lat'
        /// </summary>
        [Fact]
        public void LatTest()
        {
            // TODO unit test for the property 'Lat'
        }
        /// <summary>
        /// Test the property 'Lng'
        /// </summary>
        [Fact]
        public void LngTest()
        {
            // TODO unit test for the property 'Lng'
        }
        /// <summary>
        /// Test the property 'LocationName'
        /// </summary>
        [Fact]
        public void LocationNameTest()
        {
            // TODO unit test for the property 'LocationName'
        }
        /// <summary>
        /// Test the property 'Website'
        /// </summary>
        [Fact]
        public void WebsiteTest()
        {
            // TODO unit test for the property 'Website'
        }
        /// <summary>
        /// Test the property 'RookieYear'
        /// </summary>
        [Fact]
        public void RookieYearTest()
        {
            // TODO unit test for the property 'RookieYear'
        }
        /// <summary>
        /// Test the property 'Motto'
        /// </summary>
        [Fact]
        public void MottoTest()
        {
            // TODO unit test for the property 'Motto'
        }
        /// <summary>
        /// Test the property 'HomeChampionship'
        /// </summary>
        [Fact]
        public void HomeChampionshipTest()
        {
            // TODO unit test for the property 'HomeChampionship'
        }

    }

}
