/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TBAAPI.V3Client.Api;
using TBAAPI.V3Client.Model;
using TBAAPI.V3Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TBAAPI.V3Client.Test
{
    /// <summary>
    ///  Class for testing TeamEventStatusAllianceBackup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TeamEventStatusAllianceBackupTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TeamEventStatusAllianceBackup
        //private TeamEventStatusAllianceBackup instance;

        public TeamEventStatusAllianceBackupTests()
        {
            // TODO uncomment below to create an instance of TeamEventStatusAllianceBackup
            //instance = new TeamEventStatusAllianceBackup();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TeamEventStatusAllianceBackup
        /// </summary>
        [Fact]
        public void TeamEventStatusAllianceBackupInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TeamEventStatusAllianceBackup
            //Assert.IsInstanceOfType<TeamEventStatusAllianceBackup> (instance, "variable 'instance' is a TeamEventStatusAllianceBackup");
        }


        /// <summary>
        /// Test the property 'Out'
        /// </summary>
        [Fact]
        public void OutTest()
        {
            // TODO unit test for the property 'Out'
        }
        /// <summary>
        /// Test the property 'In'
        /// </summary>
        [Fact]
        public void InTest()
        {
            // TODO unit test for the property 'In'
        }

    }

}
