/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using TBAAPI.V3Client.Client;
using TBAAPI.V3Client.Api;
using TBAAPI.V3Client.Model;

namespace TBAAPI.V3Client.Test
{
    /// <summary>
    ///  Class for testing MatchApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MatchApiTests : IDisposable
    {
        private MatchApi instance;

        public MatchApiTests()
        {
            instance = new MatchApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MatchApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' MatchApi
            //Assert.IsType(typeof(MatchApi), instance, "instance is a MatchApi");
        }

        
        /// <summary>
        /// Test GetEventMatchTimeseries
        /// </summary>
        [Fact]
        public void GetEventMatchTimeseriesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string eventKey = null;
            //string ifModifiedSince = null;
            //var response = instance.GetEventMatchTimeseries(eventKey, ifModifiedSince);
            //Assert.IsType<List<string>> (response, "response is List<string>");
        }
        
        /// <summary>
        /// Test GetEventMatches
        /// </summary>
        [Fact]
        public void GetEventMatchesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string eventKey = null;
            //string ifModifiedSince = null;
            //var response = instance.GetEventMatches(eventKey, ifModifiedSince);
            //Assert.IsType<List<Match>> (response, "response is List<Match>");
        }
        
        /// <summary>
        /// Test GetEventMatchesKeys
        /// </summary>
        [Fact]
        public void GetEventMatchesKeysTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string eventKey = null;
            //string ifModifiedSince = null;
            //var response = instance.GetEventMatchesKeys(eventKey, ifModifiedSince);
            //Assert.IsType<List<string>> (response, "response is List<string>");
        }
        
        /// <summary>
        /// Test GetEventMatchesSimple
        /// </summary>
        [Fact]
        public void GetEventMatchesSimpleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string eventKey = null;
            //string ifModifiedSince = null;
            //var response = instance.GetEventMatchesSimple(eventKey, ifModifiedSince);
            //Assert.IsType<List<MatchSimple>> (response, "response is List<MatchSimple>");
        }
        
        /// <summary>
        /// Test GetMatch
        /// </summary>
        [Fact]
        public void GetMatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string matchKey = null;
            //string ifModifiedSince = null;
            //var response = instance.GetMatch(matchKey, ifModifiedSince);
            //Assert.IsType<Match> (response, "response is Match");
        }
        
        /// <summary>
        /// Test GetMatchSimple
        /// </summary>
        [Fact]
        public void GetMatchSimpleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string matchKey = null;
            //string ifModifiedSince = null;
            //var response = instance.GetMatchSimple(matchKey, ifModifiedSince);
            //Assert.IsType<MatchSimple> (response, "response is MatchSimple");
        }
        
        /// <summary>
        /// Test GetMatchTimeseries
        /// </summary>
        [Fact]
        public void GetMatchTimeseriesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string matchKey = null;
            //string ifModifiedSince = null;
            //var response = instance.GetMatchTimeseries(matchKey, ifModifiedSince);
            //Assert.IsType<List<Object>> (response, "response is List<Object>");
        }
        
        /// <summary>
        /// Test GetMatchZebra
        /// </summary>
        [Fact]
        public void GetMatchZebraTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string matchKey = null;
            //string ifModifiedSince = null;
            //var response = instance.GetMatchZebra(matchKey, ifModifiedSince);
            //Assert.IsType<Zebra> (response, "response is Zebra");
        }
        
        /// <summary>
        /// Test GetTeamEventMatches
        /// </summary>
        [Fact]
        public void GetTeamEventMatchesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string teamKey = null;
            //string eventKey = null;
            //string ifModifiedSince = null;
            //var response = instance.GetTeamEventMatches(teamKey, eventKey, ifModifiedSince);
            //Assert.IsType<List<Match>> (response, "response is List<Match>");
        }
        
        /// <summary>
        /// Test GetTeamEventMatchesKeys
        /// </summary>
        [Fact]
        public void GetTeamEventMatchesKeysTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string teamKey = null;
            //string eventKey = null;
            //string ifModifiedSince = null;
            //var response = instance.GetTeamEventMatchesKeys(teamKey, eventKey, ifModifiedSince);
            //Assert.IsType<List<string>> (response, "response is List<string>");
        }
        
        /// <summary>
        /// Test GetTeamEventMatchesSimple
        /// </summary>
        [Fact]
        public void GetTeamEventMatchesSimpleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string teamKey = null;
            //string eventKey = null;
            //string ifModifiedSince = null;
            //var response = instance.GetTeamEventMatchesSimple(teamKey, eventKey, ifModifiedSince);
            //Assert.IsType<List<Match>> (response, "response is List<Match>");
        }
        
        /// <summary>
        /// Test GetTeamMatchesByYear
        /// </summary>
        [Fact]
        public void GetTeamMatchesByYearTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string teamKey = null;
            //int year = null;
            //string ifModifiedSince = null;
            //var response = instance.GetTeamMatchesByYear(teamKey, year, ifModifiedSince);
            //Assert.IsType<List<Match>> (response, "response is List<Match>");
        }
        
        /// <summary>
        /// Test GetTeamMatchesByYearKeys
        /// </summary>
        [Fact]
        public void GetTeamMatchesByYearKeysTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string teamKey = null;
            //int year = null;
            //string ifModifiedSince = null;
            //var response = instance.GetTeamMatchesByYearKeys(teamKey, year, ifModifiedSince);
            //Assert.IsType<List<string>> (response, "response is List<string>");
        }
        
        /// <summary>
        /// Test GetTeamMatchesByYearSimple
        /// </summary>
        [Fact]
        public void GetTeamMatchesByYearSimpleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string teamKey = null;
            //int year = null;
            //string ifModifiedSince = null;
            //var response = instance.GetTeamMatchesByYearSimple(teamKey, year, ifModifiedSince);
            //Assert.IsType<List<MatchSimple>> (response, "response is List<MatchSimple>");
        }
        
    }

}
